//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todo.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskModel
    {
        public int Id_task { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<int> Id_usera { get; set; }
    
        public virtual UserModel UserModel { get; set; }
    }
}
